# 邮箱配置
EMAIL_ADDRESS:
EMAIL_USE_TLS: False
EMAIL_USE_SSL: True
EMAIL_HOST: smtp.qq.com
EMAIL_PORT: 465
EMAIL_HOST_USER:
EMAIL_HOST_PASSWORD:

# 数据库链接信息
DB_NAME: knowledge_latest
DB_HOST: localhost
DB_PORT: 5432
DB_USER: root
DB_PASSWORD: 123456
DB_ENGINE: django.db.backends.postgresql_psycopg2

DEBUG: false

TIME_ZONE: Asia/Shanghai


 # 模型相关配置
EMBEDDING_MODEL_PATH: model
EMBEDDING_MODEL_NAME: model/shibing624_text2vec-base-chinese